In [4]:

import pandas as pd
from pathlib import Path

%pip install sqlalchemy

from sqlalchemy import create_engine, text

Collecting sqlalchemy
  Using cached sqlalchemy-2.0.51-cp314-cp314-win_amd64.whl.metadata (9.8 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Using cached greenlet-3.5.3-cp314-cp314-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in d:\vendoriq\.venv\lib\site-packages (from sqlalchemy) (4.15.0)
Using cached sqlalchemy-2.0.51-cp314-cp314-win_amd64.whl (2.1 MB)
Using cached greenlet-3.5.3-cp314-cp314-win_amd64.whl (240 kB)
Installing collected packages: greenlet, sqlalchemy

   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   ---------------------------------------- 2/2 [sqlalchemy]

Successfully installed greenlet-3.5.3 sqlalchemy-2.0.51
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
current_path = Path.cwd()

if current_path.name == "notebooks":
    BASE_DIR = current_path.parent
else:
    BASE_DIR = current_path

DATABASE_PATH = BASE_DIR / "database" / "vendor_iq.db"

engine = create_engine(f"sqlite:///{DATABASE_PATH.as_posix()}", echo=False)

print("Database path:", DATABASE_PATH)

Database path: d:\VendorIQ\database\vendor_iq.db

In [6]:
tables = pd.read_sql_query("""
SELECT name 
FROM sqlite_master 
WHERE type = 'table';
""", engine)

tables

              name
0  begin_inventory
1    end_inventory
2  purchase_prices
3        purchases
4            sales
5   vendor_invoice

In [7]:
tables = pd.read_sql_query("""
SELECT name 
FROM sqlite_master 
WHERE type = 'table';
""", engine)

tables

              name
0  begin_inventory
1    end_inventory
2  purchase_prices
3        purchases
4            sales
5   vendor_invoice

In [8]:
with engine.connect() as conn:
    for table in tables["name"]:
        row_count = conn.execute(text(f'SELECT COUNT(*) FROM "{table}"')).scalar()
        print(f"{table}: {row_count:,} rows")

begin_inventory: 206,529 rows
end_inventory: 224,489 rows
purchase_prices: 12,261 rows
purchases: 2,372,474 rows
sales: 12,825,363 rows
vendor_invoice: 5,543 rows

In [9]:
for table in tables["name"]:
    print(f"\n--- {table} ---")
    schema = pd.read_sql_query(f'PRAGMA table_info("{table}")', engine)
    display(schema[["name", "type"]])

--- begin_inventory ---

          name    type
0  InventoryId    TEXT
1        Store  BIGINT
2         City    TEXT
3        Brand  BIGINT
4  Description    TEXT
5         Size    TEXT
6       onHand  BIGINT
7        Price   FLOAT
8    startDate    TEXT

--- end_inventory ---

          name    type
0  InventoryId    TEXT
1        Store  BIGINT
2         City    TEXT
3        Brand  BIGINT
4  Description    TEXT
5         Size    TEXT
6       onHand  BIGINT
7        Price   FLOAT
8      endDate    TEXT

--- purchase_prices ---

             name    type
0           Brand  BIGINT
1     Description    TEXT
2           Price   FLOAT
3            Size    TEXT
4          Volume    TEXT
5  Classification  BIGINT
6   PurchasePrice   FLOAT
7    VendorNumber  BIGINT
8      VendorName    TEXT

--- purchases ---

              name    type
0      InventoryId    TEXT
1            Store  BIGINT
2            Brand  BIGINT
3      Description    TEXT
4             Size    TEXT
5     VendorNumber  BIGINT
6       VendorName    TEXT
7         PONumber  BIGINT
8           PODate    TEXT
9    ReceivingDate    TEXT
10     InvoiceDate    TEXT
11         PayDate    TEXT
12   PurchasePrice   FLOAT
13        Quantity  BIGINT
14         Dollars   FLOAT
15  Classification  BIGINT

--- sales ---

              name    type
0      InventoryId    TEXT
1            Store  BIGINT
2            Brand  BIGINT
3      Description    TEXT
4             Size    TEXT
5    SalesQuantity  BIGINT
6     SalesDollars   FLOAT
7       SalesPrice   FLOAT
8        SalesDate    TEXT
9           Volume   FLOAT
10  Classification  BIGINT
11       ExciseTax   FLOAT
12        VendorNo  BIGINT
13      VendorName    TEXT

--- vendor_invoice ---

           name    type
0  VendorNumber  BIGINT
1    VendorName    TEXT
2   InvoiceDate    TEXT
3      PONumber  BIGINT
4        PODate    TEXT
5       PayDate    TEXT
6      Quantity  BIGINT
7       Dollars   FLOAT
8       Freight   FLOAT
9      Approval    TEXT

In [10]:
for table in tables["name"]:
    print(f"\n--- {table} ---")
    display(pd.read_sql_query(f'SELECT * FROM "{table}" LIMIT 5', engine))

--- begin_inventory ---

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,startDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,8,12.99,2024-01-01
1,1_HARDERSFIELD_60,1,HARDERSFIELD,60,Canadian Club 1858 VAP,750mL,7,10.99,2024-01-01
2,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,6,36.99,2024-01-01
3,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,3,38.99,2024-01-01
4,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,6,34.99,2024-01-01

--- end_inventory ---

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,endDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,11,12.99,2024-12-31
1,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,7,36.99,2024-12-31
2,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,7,38.99,2024-12-31
3,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,4,34.99,2024-12-31
4,1_HARDERSFIELD_75,1,HARDERSFIELD,75,Three Olives Tomato Vodka,750mL,7,14.99,2024-12-31

--- purchase_prices ---

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.

--- purchases ---

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,69_MOUNTMEND_8412,69,8412,Tequila Ocho Plata Fresno,750mL,105,ALTAMAR BRANDS LLC,8124,2023-12-21,2024-01-02,2024-01-04,2024-02-16,35.71,6,214.26,1
1,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
2,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
3,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
4,76_DONCASTER_2034,76,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,8169,2023-12-24,2024-01-02,2024-01-09,2024-02-16,21.32,5,106.60,1

--- sales ---

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-01,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,2,32.98,16.49,2024-01-02,750.0,1,1.57,12546,JIM BEAM BRANDS COMPANY
2,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-03,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
3,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,14.49,14.49,2024-01-08,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
4,1_HARDERSFIELD_1005,1,1005,Maker's Mark Combo Pack,375mL 2 Pk,2,69.98,34.99,2024-01-09,375.0,1,0.79,12546,JIM BEAM BRANDS COMPANY

--- vendor_invoice ---

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
2,388,ATLANTIC IMPORTING COMPANY,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.61,None
3,480,BACARDI USA INC,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.20,None
4,516,BANFI PRODUCTS CORP,2024-01-07,8170,2023-12-24,2024-02-12,1935,15527.25,429.20,None

In [11]:
for table in tables["name"]:
    print(f"\n--- Missing values in {table} ---")
    
    df_sample = pd.read_sql_query(f'SELECT * FROM "{table}" LIMIT 10000', engine)
    
    missing_values = df_sample.isnull().sum()
    missing_values = missing_values[missing_values > 0]
    
    if missing_values.empty:
        print("No missing values found in sample.")
    else:
        display(missing_values)

--- Missing values in begin_inventory ---
No missing values found in sample.

--- Missing values in end_inventory ---
No missing values found in sample.

--- Missing values in purchase_prices ---

Description    1
Size           1
Volume         1
dtype: int64

--- Missing values in purchases ---
No missing values found in sample.

--- Missing values in sales ---
No missing values found in sample.

--- Missing values in vendor_invoice ---

Approval    5169
dtype: int64

In [13]:
small_tables = ["purchase_prices", "vendor_invoice", "begin_inventory", "end_inventory"]

for table in small_tables:
    print(f"\n--- Duplicate check: {table} ---")
    
    df = pd.read_sql_query(f'SELECT * FROM "{table}"', engine)
    
    duplicate_count = df.duplicated().sum()
    print(f"Duplicate rows: {duplicate_count}")

--- Duplicate check: purchase_prices ---
Duplicate rows: 0

--- Duplicate check: vendor_invoice ---
Duplicate rows: 0

--- Duplicate check: begin_inventory ---
Duplicate rows: 0

--- Duplicate check: end_inventory ---
Duplicate rows: 0

In [14]:
date_checks = {
    "sales": "SalesDate",
    "purchases": "PODate",
    "begin_inventory": "startDate",
    "end_inventory": "endDate"
}

for table, date_col in date_checks.items():
    query = f"""
    SELECT 
        MIN("{date_col}") AS min_date,
        MAX("{date_col}") AS max_date
    FROM "{table}";
    """
    
    print(f"\n--- Date range: {table} ---")
    display(pd.read_sql_query(query, engine))

--- Date range: sales ---

     min_date    max_date
0  2024-01-01  2024-12-31

--- Date range: purchases ---

     min_date    max_date
0  2023-12-20  2024-12-23

--- Date range: begin_inventory ---

     min_date    max_date
0  2024-01-01  2024-01-01

--- Date range: end_inventory ---

     min_date    max_date
0  2024-12-31  2024-12-31

In [3]:
import pandas as pd
from pathlib import Path
from sqlalchemy import create_engine

current_path = Path.cwd()

if current_path.name == "notebooks":
    BASE_DIR = current_path.parent
else:
    BASE_DIR = current_path

DATABASE_PATH = BASE_DIR / "database" / "vendor_iq.db"

engine = create_engine(f"sqlite:///{DATABASE_PATH.as_posix()}", echo=False)

print("Connected to:", DATABASE_PATH)

Connected to: d:\VendorIQ\database\vendor_iq.db

In [4]:
key_checks = {
    "begin_inventory": ["InventoryId", "Brand"],
    "end_inventory": ["InventoryId", "Brand"],
    "purchase_prices": ["Brand", "VendorNumber"],
    "purchases": ["InventoryId", "Brand", "VendorNumber", "PONumber"],
    "sales": ["InventoryId", "Brand", "VendorNo"],
    "vendor_invoice": ["VendorNumber", "PONumber"]
}

for table, columns in key_checks.items():
    print(f"\n--- Unique key counts: {table} ---")
    
    for column in columns:
        query = f"""
        SELECT COUNT(DISTINCT "{column}") AS unique_count
        FROM "{table}";
        """
        
        result = pd.read_sql_query(query, engine)
        print(f"{column}: {result['unique_count'][0]:,}")

--- Unique key counts: begin_inventory ---
InventoryId: 206,529
Brand: 8,094

--- Unique key counts: end_inventory ---
InventoryId: 224,489
Brand: 9,653

--- Unique key counts: purchase_prices ---
Brand: 12,261
VendorNumber: 131

--- Unique key counts: purchases ---
InventoryId: 245,907
Brand: 10,664
VendorNumber: 126
PONumber: 5,543

--- Unique key counts: sales ---
InventoryId: 267,552
Brand: 11,237
VendorNo: 127

--- Unique key counts: vendor_invoice ---
VendorNumber: 126
PONumber: 5,543

In [2]:
import pandas as pd
from pathlib import Path
from sqlalchemy import create_engine

current_path = Path.cwd()

if current_path.name == "notebooks":
    BASE_DIR = current_path.parent
else:
    BASE_DIR = current_path

DATABASE_PATH = BASE_DIR / "database" / "vendor_iq.db"

engine = create_engine(f"sqlite:///{DATABASE_PATH.as_posix()}", echo=False)

print("Connected to:", DATABASE_PATH)

Connected to: d:\VendorIQ\database\vendor_iq.db

In [3]:
vendor_match_query = """
WITH sales_vendors AS (
    SELECT DISTINCT VendorNo AS VendorNumber
    FROM sales
),
purchase_vendors AS (
    SELECT DISTINCT VendorNumber
    FROM purchases
)

SELECT 
    'Vendors in sales' AS category,
    COUNT(*) AS vendor_count
FROM sales_vendors

UNION ALL

SELECT 
    'Vendors in purchases' AS category,
    COUNT(*) AS vendor_count
FROM purchase_vendors

UNION ALL

SELECT 
    'Vendors in both sales and purchases' AS category,
    COUNT(*) AS vendor_count
FROM sales_vendors
INNER JOIN purchase_vendors
    ON sales_vendors.VendorNumber = purchase_vendors.VendorNumber;
"""

vendor_match = pd.read_sql_query(vendor_match_query, engine)

vendor_match

                              category  vendor_count
0                     Vendors in sales           127
1                 Vendors in purchases           126
2  Vendors in both sales and purchases           124

In [4]:
unmatched_vendors_query = """
WITH sales_vendors AS (
    SELECT DISTINCT 
        VendorNo AS VendorNumber,
        VendorName
    FROM sales
),
purchase_vendors AS (
    SELECT DISTINCT 
        VendorNumber,
        VendorName
    FROM purchases
)

SELECT 
    'Only in sales' AS match_status,
    sales_vendors.VendorNumber,
    sales_vendors.VendorName
FROM sales_vendors
LEFT JOIN purchase_vendors
    ON sales_vendors.VendorNumber = purchase_vendors.VendorNumber
WHERE purchase_vendors.VendorNumber IS NULL

UNION ALL

SELECT 
    'Only in purchases' AS match_status,
    purchase_vendors.VendorNumber,
    purchase_vendors.VendorName
FROM purchase_vendors
LEFT JOIN sales_vendors
    ON purchase_vendors.VendorNumber = sales_vendors.VendorNumber
WHERE sales_vendors.VendorNumber IS NULL;
"""

unmatched_vendors = pd.read_sql_query(unmatched_vendors_query, engine)

unmatched_vendors

        match_status  VendorNumber                   VendorName
0      Only in sales          9710  WHYTE & MACKAY
1      Only in sales          1002  BERNIKO LLC
2      Only in sales         90034  EXCLUSIVE WINES & SPIRITS
3  Only in purchases          4901  LAUREATE IMPORTS CO
4  Only in purchases            54  AAPER ALCOHOL & CHEMICAL CO

In [5]:
brand_match_query = """
WITH sales_brands AS (
    SELECT DISTINCT Brand
    FROM sales
),
purchase_brands AS (
    SELECT DISTINCT Brand
    FROM purchases
),
price_brands AS (
    SELECT DISTINCT Brand
    FROM purchase_prices
)

SELECT 
    'Brands in sales' AS category,
    COUNT(*) AS brand_count
FROM sales_brands

UNION ALL

SELECT 
    'Brands in purchases' AS category,
    COUNT(*) AS brand_count
FROM purchase_brands

UNION ALL

SELECT 
    'Brands in purchase_prices' AS category,
    COUNT(*) AS brand_count
FROM price_brands

UNION ALL

SELECT 
    'Brands in both sales and purchases' AS category,
    COUNT(*) AS brand_count
FROM sales_brands
INNER JOIN purchase_brands
    ON sales_brands.Brand = purchase_brands.Brand

UNION ALL

SELECT 
    'Brands in sales, purchases, and purchase_prices' AS category,
    COUNT(*) AS brand_count
FROM sales_brands
INNER JOIN purchase_brands
    ON sales_brands.Brand = purchase_brands.Brand
INNER JOIN price_brands
    ON sales_brands.Brand = price_brands.Brand;
"""

brand_match = pd.read_sql_query(brand_match_query, engine)

brand_match

                                          category  brand_count
0                                  Brands in sales        11237
1                              Brands in purchases        10664
2                        Brands in purchase_prices        12261
3               Brands in both sales and purchases        10486
4  Brands in sales, purchases, and purchase_prices        10486

In [6]:
sales_summary_query = """
SELECT
    VendorNo AS VendorNumber,
    VendorName,
    Brand,
    Description,
    SUM(SalesQuantity) AS total_sales_quantity,
    SUM(SalesDollars) AS total_sales_dollars,
    AVG(SalesPrice) AS avg_sales_price
FROM sales
GROUP BY 
    VendorNo,
    VendorName,
    Brand,
    Description
ORDER BY total_sales_dollars DESC;
"""

sales_summary = pd.read_sql_query(sales_summary_query, engine)

sales_summary.head()

,VendorNumber,VendorName,Brand,Description,total_sales_quantity,total_sales_dollars,avg_sales_price
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,142049,5101919.51,36.233470
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,160247,4819073.49,30.314332
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,187140,4538120.60,24.483151
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,200412,4475972.88,22.830046
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,135838,4223107.62,31.417124

In [7]:
purchase_summary_query = """
SELECT
    VendorNumber,
    VendorName,
    Brand,
    Description,
    SUM(Quantity) AS total_purchase_quantity,
    SUM(Dollars) AS total_purchase_dollars,
    AVG(PurchasePrice) AS avg_purchase_price
FROM purchases
GROUP BY
    VendorNumber,
    VendorName,
    Brand,
    Description
ORDER BY total_purchase_dollars DESC;
"""

purchase_summary = pd.read_sql_query(purchase_summary_query, engine)

purchase_summary.head()

,VendorNumber,VendorName,Brand,Description,total_purchase_quantity,total_purchase_dollars,avg_purchase_price
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,145080,3811251.60,26.27
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,164038,3804041.22,23.19
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,187407,3418303.68,18.24
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,201682,3261197.94,16.17
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,138109,3023206.01,21.89

In [8]:
vendor_brand_summary_query = """
WITH sales_summary AS (
    SELECT
        VendorNo AS VendorNumber,
        VendorName,
        Brand,
        Description,
        SUM(SalesQuantity) AS total_sales_quantity,
        SUM(SalesDollars) AS total_sales_dollars,
        AVG(SalesPrice) AS avg_sales_price
    FROM sales
    GROUP BY 
        VendorNo,
        VendorName,
        Brand,
        Description
),

purchase_summary AS (
    SELECT
        VendorNumber,
        VendorName,
        Brand,
        Description,
        SUM(Quantity) AS total_purchase_quantity,
        SUM(Dollars) AS total_purchase_dollars,
        AVG(PurchasePrice) AS avg_purchase_price
    FROM purchases
    GROUP BY
        VendorNumber,
        VendorName,
        Brand,
        Description
)

SELECT
    p.VendorNumber,
    p.VendorName,
    p.Brand,
    p.Description,
    p.total_purchase_quantity,
    p.total_purchase_dollars,
    p.avg_purchase_price,
    s.total_sales_quantity,
    s.total_sales_dollars,
    s.avg_sales_price,
    s.total_sales_dollars - p.total_purchase_dollars AS gross_profit,
    ROUND(
        (s.total_sales_dollars - p.total_purchase_dollars) * 100.0 
        / s.total_sales_dollars, 
        2
    ) AS profit_margin_percent,
    p.total_purchase_quantity - s.total_sales_quantity AS unsold_quantity
FROM purchase_summary p
INNER JOIN sales_summary s
    ON p.VendorNumber = s.VendorNumber
    AND p.Brand = s.Brand
ORDER BY gross_profit DESC;
"""

vendor_brand_summary = pd.read_sql_query(vendor_brand_summary_query, engine)

vendor_brand_summary.head()

,VendorNumber,VendorName,Brand,Description,total_purchase_quantity,total_purchase_dollars,avg_purchase_price,total_sales_quantity,total_sales_dollars,avg_sales_price,gross_profit,profit_margin_percent,unsold_quantity
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,145080,3811251.60,26.27,142049,5101919.51,36.233470,1290667.91,25.30,3031
1,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,201682,3261197.94,16.17,200412,4475972.88,22.830046,1214774.94,27.14,1270
2,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,138109,3023206.01,21.89,135838,4223107.62,31.417124,1199901.61,28.41,2271
3,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,187407,3418303.68,18.24,187140,4538120.60,24.483151,1119816.92,24.68,267
4,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,164038,3804041.22,23.19,160247,4819073.49,30.314332,1015032.27,21.06,3791

In [9]:
create_vendor_brand_summary_query = """
DROP TABLE IF EXISTS vendor_brand_summary;

CREATE TABLE vendor_brand_summary AS
WITH sales_summary AS (
    SELECT
        VendorNo AS VendorNumber,
        VendorName,
        Brand,
        Description,
        SUM(SalesQuantity) AS total_sales_quantity,
        SUM(SalesDollars) AS total_sales_dollars,
        AVG(SalesPrice) AS avg_sales_price
    FROM sales
    GROUP BY 
        VendorNo,
        VendorName,
        Brand,
        Description
),

purchase_summary AS (
    SELECT
        VendorNumber,
        VendorName,
        Brand,
        Description,
        SUM(Quantity) AS total_purchase_quantity,
        SUM(Dollars) AS total_purchase_dollars,
        AVG(PurchasePrice) AS avg_purchase_price
    FROM purchases
    GROUP BY
        VendorNumber,
        VendorName,
        Brand,
        Description
)

SELECT
    p.VendorNumber,
    p.VendorName,
    p.Brand,
    p.Description,
    p.total_purchase_quantity,
    p.total_purchase_dollars,
    p.avg_purchase_price,
    s.total_sales_quantity,
    s.total_sales_dollars,
    s.avg_sales_price,
    s.total_sales_dollars - p.total_purchase_dollars AS gross_profit,
    ROUND(
        (s.total_sales_dollars - p.total_purchase_dollars) * 100.0 
        / s.total_sales_dollars, 
        2
    ) AS profit_margin_percent,
    p.total_purchase_quantity - s.total_sales_quantity AS unsold_quantity
FROM purchase_summary p
INNER JOIN sales_summary s
    ON p.VendorNumber = s.VendorNumber
    AND p.Brand = s.Brand;
"""

In [10]:
from sqlalchemy import text

with engine.begin() as conn:
    for statement in create_vendor_brand_summary_query.strip().split(";"):
        if statement.strip():
            conn.execute(text(statement))

In [1]:
import pandas as pd
from pathlib import Path
from sqlalchemy import create_engine

current_path = Path.cwd()

if current_path.name == "notebooks":
    BASE_DIR = current_path.parent
else:
    BASE_DIR = current_path

DATABASE_PATH = BASE_DIR / "database" / "vendor_iq.db"

engine = create_engine(f"sqlite:///{DATABASE_PATH.as_posix()}", echo=False)

print("Connected to:", DATABASE_PATH)

Connected to: d:\VendorIQ\database\vendor_iq.db

In [2]:
pd.read_sql_query("""
SELECT *
FROM vendor_brand_summary
LIMIT 5;
""", engine)

,VendorNumber,VendorName,Brand,Description,total_purchase_quantity,total_purchase_dollars,avg_purchase_price,total_sales_quantity,total_sales_dollars,avg_sales_price,gross_profit,profit_margin_percent,unsold_quantity
0,2,"IRA GOLDMAN AND WILLIAMS, LLP",90085,Ch Lilian 09 Ladouys St Este,8,190.88,23.86,18,665.82,36.990000,474.94,71.33,-10
1,2,"IRA GOLDMAN AND WILLIAMS, LLP",90609,Flavor Essence Variety 5 Pak,320,5440.00,17.00,24,599.76,24.990000,-4840.24,-807.03,296
2,60,ADAMBA IMPORTS INTL INC,771,Bak's Krupnik Honey Liqueur,39,446.16,11.44,47,704.53,14.990000,258.37,36.67,-8
3,60,ADAMBA IMPORTS INTL INC,3979,Vesica Potato Vodka,4687,76257.49,16.27,3931,66871.69,17.020216,-9385.80,-14.04,756
4,105,ALTAMAR BRANDS LLC,2529,Right Gin,12,279.00,23.25,12,359.88,29.990000,80.88,22.47,0

In [3]:
pd.read_sql_query("""
SELECT COUNT(*) AS total_rows
FROM vendor_brand_summary;
""", engine)

   total_rows
0       10515

In [4]:
from sqlalchemy import text

In [5]:
create_vendor_performance_summary_query = """
DROP TABLE IF EXISTS vendor_performance_summary;

CREATE TABLE vendor_performance_summary AS
WITH sales_summary AS (
    SELECT
        VendorNo AS VendorNumber,
        VendorName,
        Brand,
        Description,
        SUM(SalesQuantity) AS total_sales_quantity,
        SUM(SalesDollars) AS total_sales_dollars,
        AVG(SalesPrice) AS avg_sales_price
    FROM sales
    GROUP BY 
        VendorNo,
        VendorName,
        Brand,
        Description
),

purchase_summary AS (
    SELECT
        VendorNumber,
        VendorName,
        Brand,
        Description,
        SUM(Quantity) AS total_purchase_quantity,
        SUM(Dollars) AS total_purchase_dollars,
        AVG(PurchasePrice) AS avg_purchase_price
    FROM purchases
    GROUP BY
        VendorNumber,
        VendorName,
        Brand,
        Description
)

SELECT
    p.VendorNumber,
    p.VendorName,
    p.Brand,
    p.Description,

    p.total_purchase_quantity,
    p.total_purchase_dollars,
    ROUND(p.avg_purchase_price, 2) AS avg_purchase_price,

    s.total_sales_quantity,
    s.total_sales_dollars,
    ROUND(s.avg_sales_price, 2) AS avg_sales_price,

    ROUND(s.total_sales_dollars - p.total_purchase_dollars, 2) AS gross_profit,

    ROUND(
        (s.total_sales_dollars - p.total_purchase_dollars) * 100.0 
        / NULLIF(s.total_sales_dollars, 0), 
        2
    ) AS profit_margin_percent,

    p.total_purchase_quantity - s.total_sales_quantity AS unsold_quantity,

    ROUND(
        s.total_sales_quantity * 1.0 / NULLIF(p.total_purchase_quantity, 0),
        2
    ) AS sales_to_purchase_qty_ratio,

    ROUND(
        s.total_sales_dollars * 1.0 / NULLIF(p.total_purchase_dollars, 0),
        2
    ) AS sales_to_purchase_value_ratio

FROM purchase_summary p
INNER JOIN sales_summary s
    ON p.VendorNumber = s.VendorNumber
    AND p.Brand = s.Brand;
"""

In [6]:
with engine.begin() as conn:
    for statement in create_vendor_performance_summary_query.strip().split(";"):
        if statement.strip():
            conn.execute(text(statement))

In [7]:
pd.read_sql_query("""
SELECT *
FROM vendor_performance_summary
LIMIT 5;
""", engine)

,VendorNumber,VendorName,Brand,Description,total_purchase_quantity,total_purchase_dollars,avg_purchase_price,total_sales_quantity,total_sales_dollars,avg_sales_price,gross_profit,profit_margin_percent,unsold_quantity,sales_to_purchase_qty_ratio,sales_to_purchase_value_ratio
0,2,"IRA GOLDMAN AND WILLIAMS, LLP",90085,Ch Lilian 09 Ladouys St Este,8,190.88,23.86,18,665.82,36.99,474.94,71.33,-10,2.25,3.49
1,2,"IRA GOLDMAN AND WILLIAMS, LLP",90609,Flavor Essence Variety 5 Pak,320,5440.00,17.00,24,599.76,24.99,-4840.24,-807.03,296,0.07,0.11
2,60,ADAMBA IMPORTS INTL INC,771,Bak's Krupnik Honey Liqueur,39,446.16,11.44,47,704.53,14.99,258.37,36.67,-8,1.21,1.58
3,60,ADAMBA IMPORTS INTL INC,3979,Vesica Potato Vodka,4687,76257.49,16.27,3931,66871.69,17.02,-9385.80,-14.04,756,0.84,0.88
4,105,ALTAMAR BRANDS LLC,2529,Right Gin,12,279.00,23.25,12,359.88,29.99,80.88,22.47,0,1.00,1.29

In [8]:
pd.read_sql_query("""
SELECT COUNT(*) AS total_rows
FROM vendor_performance_summary;
""", engine)

   total_rows
0       10515